services:
  back-end:
    image: back-end-prod
    container_name: back-end-container-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - my-mongo
    restart: always

  my-mongo:
    image: mongo:latest
    container_name: mongodb-container-dev
    volumes:
      - mongo-db-volume:/data/db
    restart: always

volumes:
  mongo-db-volume:
